<?php

namespace Plugin\AmazonPayMini\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\AmazonPayMini\Entity\Config;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @return Config|null
     */
    public function get()
    {
        return $this->findOneBy([]);
    }
}
